# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/edit-tags.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTagsDialog(object):
    def setupUi(self, EditTagsDialog):
        EditTagsDialog.setObjectName("EditTagsDialog")
        EditTagsDialog.resize(420, 373)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditTagsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 330, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.moveUpButton = QtWidgets.QPushButton(EditTagsDialog)
        self.moveUpButton.setGeometry(QtCore.QRect(10, 120, 51, 31))
        self.moveUpButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.moveUpButton.setStyleSheet("text-align: center")
        self.moveUpButton.setText("")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.moveUpButton.setIcon(icon)
        self.moveUpButton.setObjectName("moveUpButton")
        self.listView = QtWidgets.QListView(EditTagsDialog)
        self.listView.setGeometry(QtCore.QRect(80, 10, 321, 311))
        self.listView.setObjectName("listView")
        self.moveDownButton = QtWidgets.QPushButton(EditTagsDialog)
        self.moveDownButton.setGeometry(QtCore.QRect(10, 160, 51, 31))
        self.moveDownButton.setText("")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.moveDownButton.setIcon(icon)
        self.moveDownButton.setObjectName("moveDownButton")
        self.editTagButton = QtWidgets.QPushButton(EditTagsDialog)
        self.editTagButton.setGeometry(QtCore.QRect(10, 330, 89, 25))
        icon = QtGui.QIcon.fromTheme("edit")
        self.editTagButton.setIcon(icon)
        self.editTagButton.setObjectName("editTagButton")

        self.retranslateUi(EditTagsDialog)
        self.buttonBox.accepted.connect(EditTagsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EditTagsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditTagsDialog)

    def retranslateUi(self, EditTagsDialog):
        _translate = QtCore.QCoreApplication.translate
        EditTagsDialog.setWindowTitle(_translate("EditTagsDialog", "Edit Tags"))
        self.editTagButton.setText(_translate("EditTagsDialog", "Edit"))
